UkrainianAktiv/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UkrainianAktiv.ViewModels;

namespace UkrainianAktiv.Controllers
{
    public class FeedbackController : Controller
    {
        [Route("enrol")]
        public IActionResult Enrol()
        {
            return View();
        }

        [Route("enrol")]
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Enrol([FromForm] ClientMessageDto message)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View(message);
        }
    }
}

UkrainianAktiv/Views/Feedback/Enrol.cshtml
@using UkrainianAktiv.ViewModels
@model ClientMessageDto

@{
    ViewBag.Title = " Запис на захід";
    Layout = "_Layout";
}

<section id="contact-page" name="request" class="animated">
    <div class="container">
        <div class="center wow fadeInDown">
            <h2>Запис на захід</h2>
            <p class="lead">Для того, щоб зв'язатись з нами, заповніть форму</p>
        </div>

        <div class="row contact-wrap wow fadeInDown">
            <form class="contact-form form-horizontal" asp-action="Enrol" asp-controller="Feedback" asp-anti-forgery="true">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone"></label>
                        <input asp-for="Phone" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="MessageText"></label>
                        <textarea asp-for="MessageText" class="form-control" rows="2"></textarea>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" name="submit" class="btn btn-primary btn-lg">
                            Відправити заявку
                        </button>
                    </div>
                </div>
            </form>
        </div> 
        <div class="row contact-wrap wow fadeInDown error-list">
            <div class="center text-danger" asp-validation-summary="All"></div>
        </div>
    </div> 
</section>  